FORMAT: 1A
HOST: http://www.google.com

# open-source-report-card
Users API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Users
User related resources of the **Users API**

## Users Collection [/users]
### List all Users [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]


## User [/users/{username}]
A single user object with all its details
Meta Data provided by a `meta_data` object

+ Parameters
    + id (required, text, `mojombo`) ... text `username` matching the github login.

### Retrieve a User [GET]
+ Response 200 (application/json)

    + Body
            {
                user: {

                },
                meta_object: {
                    total_users: 11,
                    busy_users: [],
                    popular_users: []
                }
            }
